stages:
  - publish

publish-job:
  stage: publish
  only:
    - tags
  tags:
    - moreillon
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  script:
    - npm publish
